-- 001_initial_schema.sql
-- Converted from MySQL schema to PostgreSQL for Supabase

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- users profile table linked to auth.users
CREATE TABLE IF NOT EXISTS public.users (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name varchar(150) NOT NULL,
  email varchar(255) NOT NULL,
  phone varchar(20),
  role varchar(20) NOT NULL DEFAULT 'farmer',
  location varchar(255),
  profile_image varchar(255),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON public.users(email);
CREATE INDEX IF NOT EXISTS idx_users_role ON public.users(role);

-- plants
CREATE TABLE IF NOT EXISTS public.plants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plant_name varchar(150) NOT NULL,
  scientific_name varchar(200),
  category varchar(100),
  description text,
  image_url varchar(255),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_plants_name ON public.plants(plant_name);
CREATE INDEX IF NOT EXISTS idx_plants_category ON public.plants(category);

-- diseases
CREATE TABLE IF NOT EXISTS public.diseases (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plant_id bigint NOT NULL REFERENCES public.plants(id) ON DELETE CASCADE,
  disease_name varchar(200) NOT NULL,
  description text,
  symptoms text,
  prevention text,
  treatment text,
  severity varchar(20) DEFAULT 'medium',
  image_url varchar(255),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_diseases_plant_id ON public.diseases(plant_id);

-- disease_predictions
CREATE TABLE IF NOT EXISTS public.disease_predictions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  plant_id bigint NOT NULL REFERENCES public.plants(id) ON DELETE CASCADE,
  disease_id bigint REFERENCES public.diseases(id),
  image_path text NOT NULL,
  predicted_class varchar(200) NOT NULL,
  confidence_score numeric(5,2) NOT NULL DEFAULT 0.00,
  prediction_status varchar(50) NOT NULL DEFAULT 'unknown',
  processing_time_ms integer,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_disease_predictions_user_id ON public.disease_predictions(user_id);

-- crops
CREATE TABLE IF NOT EXISTS public.crops (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  crop_name varchar(150) NOT NULL,
  scientific_name varchar(200),
  description text,
  season varchar(100),
  soil_type varchar(100),
  water_requirement varchar(100),
  temperature_min numeric(5,2),
  temperature_max numeric(5,2),
  ph_min numeric(4,2),
  ph_max numeric(4,2),
  rainfall_min numeric(8,2),
  rainfall_max numeric(8,2),
  growing_period_days integer,
  image_url varchar(255),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_crops_name ON public.crops(crop_name);

-- crop_recommendations
CREATE TABLE IF NOT EXISTS public.crop_recommendations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nitrogen numeric(8,2) NOT NULL,
  phosphorus numeric(8,2) NOT NULL,
  potassium numeric(8,2) NOT NULL,
  temperature numeric(5,2) NOT NULL,
  humidity numeric(5,2) NOT NULL,
  ph numeric(4,2) NOT NULL,
  rainfall numeric(8,2) NOT NULL,
  recommended_crop_id bigint NOT NULL REFERENCES public.crops(id) ON DELETE CASCADE,
  confidence_score numeric(5,2) NOT NULL DEFAULT 0.00,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- audit_logs
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id),
  event_type varchar(100) NOT NULL,
  message text NOT NULL,
  metadata jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Additional indexes
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON public.audit_logs(user_id);
